server:
  servlet:
    context-path: /savings
  port: 8080
spring:
  profiles:
    active: "local"
  main:
    banner-mode: "off"
  application:
    name: Savings service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/?replicaSet=rs0&retryWrites=true
      database: savings
  jackson:
    date-format: dd/MM/yyyy
  servlet:
    multipart:
      enabled:true
    max-file-size: 300KB

logging:
  level:
    org.soneira.savings: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
