version: '3.8'
services:
  mongodb:
    image: mongo:7.0.4
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - "./volumes/mongo1:/data/db"
      - "./resources/mongo/1-init.js:/docker-entrypoint-initdb.d/1-init.js:ro"
      - "./resources/mongo/2-import.sh:/docker-entrypoint-initdb.d/2-import.sh"
      - "./resources/mongo/categories.json:/categories.json"
      - "./resources/mongo/subcategories.json:/subcategories.json"
      - "./resources/mongo/user.json:/user.json"
    ports:
      - '27017:27017'