server:
  servlet:
    context-path: /savings
  port: 8080
spring:
  profiles:
    active: "local"
  main:
    banner-mode: "off"
  application:
    name: Savings service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  jackson:
    date-format: dd/MM/yyyy
  servlet:
    multipart:
      enabled:true
    max-file-size: 300KB

logging:
  level:
    org.soneira.savings: INFO
    org.springframework.data.mongodb.core.MongoTemplate: ERROR
    org.springframework.transaction.interceptor: ERROR
