version: '3.9'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGODB_REPLICA_SET_KEY=${MONGO_RS_KEY}

    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    restart: always
    depends_on:
      - mongodb-primary
    ports:
      - 27027:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_PASS}
      - MONGODB_REPLICA_SET_KEY=${MONGO_RS_KEY}

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    restart: always
    depends_on:
      - mongodb-primary
    ports:
      - 27037:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_PASS}
      - MONGODB_REPLICA_SET_KEY=${MONGO_RS_KEY}

volumes:
  mongodb_master_data:
    driver: local